version: "3.8"

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    networks:
      bank_net:
        ipv4_address: 172.28.1.1

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ambelnok@ukr.net
      PGADMIN_DEFAULT_PASSWORD: 1qaz2wsx
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    networks:
      bank_net:
        ipv4_address: 172.28.1.2
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    networks:
      bank_net:
        ipv4_address: 172.28.1.3

volumes:
  db-data:
  pgadmin-data:
  redis-data:

networks:
  bank_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16